### ISSUE TITLE
Universal card search

### ISSUE THREAD

**Issue by DanJohnson** [ANRDigital/ANR-Deck-Builder#1]
I want to be able to search for, and view a card from any point in the app.

Currently I have to browse by set, or be editing a deck.

**Comment by tblackwe** [comment]
This one was my request. I can take a look at after I get the build setup

-BeardedThomas

**Comment by danj3000** [comment]
Great. What kind of UI do you think would work? do you think an app burger menu is a good idea? items could be decks, search, browse (like current cards icon) ?

**Comment by tblackwe** [comment]
works been a bit crazy. but getting project setup this weekend.

**Comment by danj3000** [comment]
I've replaced the set browser with a basic search by text and filter by pack. I'll close this issue and create another for introduction of a nav drawer
