### ISSUE TITLE
Events and Operations show up in wrong decks

### ISSUE THREAD

**Issue by Proto-Fox** [ANRDigital/ANR-Deck-Builder#80]
In Corp decks an empty "Event" category shows up.
In Runner decks an empty "Operations" category shows up.
They can be seen in every deck under "My Cards" and under "Cards".

**Comment by danj3000** [comment]
This is being caused by some data errors in netrunnerdb. 2 terminal directive cards are categorised wrongly:
Security leak
Net watchlist

The sections are dynamic, so dictated by the data
